data:
  output_filename: eeg_data.h5
  processed_dir: data/processed
  raw_dir: data/organized
dataloader:
  batch_size: 64
  mode: siamese
  num_workers: 4
  pin_memory: true
  seed: 42
  siamese:
    cache_pairs: false
    pairs_cache_dir: data/cache
    pos_ratio: 0.5
    same_session: true
    use_contrastive: false
  test_size: 0.2
evaluation:
  model_path: models/best_model.pt
  output_dir: results
  plot_results: true
experiment:
  include_eyes_closed: false
  include_eyes_open: true
model:
  conv_filters:
  - 32
  - 32
  - 32
  dropout_rate: 0.2760184807695273
  fc_dim: 512
  ica_components: 128
  improved:
    batch_norm: false
    enabled: true
    residual: true
    skip_stride:
    - 4
    - 1
  kernel_sizes:
  - - 5
    - 5
  - - 3
    - 3
  - - 3
    - 3
  siamese:
    attention:
      enabled: true
      reduction_ratio: 8
    embedding_dim: 512
    hidden_dim: 128
    margin: 1.0
    similarity_network:
      additional_layer: true
      dropout_reduction: 0.47005532348586243
      use_batch_norm: true
preprocessing:
  channels:
    select: true
    set: epoc_x
  filter:
    apply: true
    highcut: 37.170439818074264
    lowcut: 1.8063752200224608
  normalize: true
  resample:
    apply: false
    freq: 128
training:
  early_stopping: true
  epochs: 30
  learning_rate: 0.004814070051379834
  optimizer: adam
  patience: 15
  use_gpu: true
  weight_decay: 5.740102924765501e-05
windowing:
  window_length: 0.5
  window_stride: 0.125
