data:
  output_filename: eeg_data.h5
  processed_dir: data/processed
  raw_dir: data/organized
dataloader:
  batch_size: 64
  mode: siamese
  num_workers: 4
  pin_memory: true
  seed: 42
  siamese:
    cache_pairs: false
    pairs_cache_dir: data/cache
    pos_ratio: 0.5
    same_session: true
    use_contrastive: false
  test_size: 0.2
evaluation:
  model_path: models/best_model.pt
  output_dir: results
  plot_results: true
experiment:
  include_eyes_closed: true
  include_eyes_open: true
model:
  conv_filters:
  - 32
  - 32
  - 32
  dropout_rate: 0.49034709340476745
  fc_dim: 128
  ica_components: 64
  kernel_sizes:
  - - 3
    - 3
  - - 3
    - 3
  - - 3
    - 3
  siamese:
    embedding_dim: 128
    hidden_dim: 64
    margin: 1.0
preprocessing:
  channels:
    select: true
    set: epoc_x
  filter:
    apply: true
    highcut: 45.628703647922414
    lowcut: 3.1503817781769023
  normalize: true
  resample:
    apply: false
    freq: 128
training:
  early_stopping: true
  epochs: 20
  learning_rate: 0.009795624180611199
  optimizer: sgd
  patience: 15
  use_gpu: true
  weight_decay: 0.0002338650916737274
windowing:
  window_length: 0.5
  window_stride: 0.25
