data:
  output_filename: eeg_data.h5
  processed_dir: data/processed
  raw_dir: data/organized
dataloader:
  batch_size: 64
  mode: siamese
  num_workers: 4
  pin_memory: true
  seed: 42
  siamese:
    cache_pairs: true
    pairs_cache_dir: data/cache
    pos_ratio: 0.5
    same_session: true
    use_contrastive: false
  test_size: 0.2
evaluation:
  model_path: models/best_model.pt
  output_dir: results
  plot_results: true
experiment:
  include_eyes_closed: false
  include_eyes_open: true
model:
  conv_filters:
  - 32
  - 32
  - 32
  dropout_rate: 0.49034709340476745
  fc_dim: 128
  ica_components: 64
  kernel_sizes:
  - - 3
    - 3
  - - 3
    - 3
  - - 3
    - 3
  # 添加改进模型所需的新参数
  improved:
    enabled: true  # 是否启用改进版模型
    batch_norm: true  # 是否使用批归一化
    residual: true  # 是否使用残差连接
    skip_stride: [4, 2]  # 跳跃连接的步长
  
  siamese:
    embedding_dim: 128
    hidden_dim: 64
    margin: 1.0

    attention:
      enabled: true  # 是否启用注意力机制
      reduction_ratio: 4  # 注意力降维比例
    
    # 改进版相似度网络配置
    similarity_network:
      use_batch_norm: true  # 是否在相似度网络中使用批归一化
      additional_layer: true  # 是否添加额外的中间层
      dropout_reduction: 0.5  # 额外层的dropout降低系数
    
preprocessing:
  channels:
    select: true
    set: epoc_x
  filter:
    apply: true
    highcut: 45.628703647922414
    lowcut: 3.1503817781769023
  normalize: true
  resample:
    apply: false
    freq: 128
training:
  early_stopping: true
  epochs: 80
  learning_rate: 0.009795624180611199
  optimizer: sgd
  patience: 15
  use_gpu: true
  weight_decay: 0.0002338650916737274
windowing:
  window_length: 0.5
  window_stride: 0.5
