data:
  output_filename: eeg_data.h5
  processed_dir: data/processed
  raw_dir: data/organized
dataloader:
  batch_size: 64
  mode: siamese # Options: 'siamese', 'identity'
  num_workers: 4
  pin_memory: true
  seed: 42
  siamese:
    pos_ratio: 0.5  # Ratio of positive pairs (same subject) to all pairs
    same_session: true  # Whether to only compare within the same session
    use_contrastive: true  # Whether to use contrastive loss instead of BCE
    cache_pairs: true  # Cache generated pairs to HDF5 file
    pairs_cache_dir: 'data/cache'  # Directory to store pairs cache
  test_size: 0.2
evaluation:
  model_path: models/best_model.pt
  output_dir: results
  plot_results: true
experiment:
  include_eyes_closed: true
  include_eyes_open: true
model:
  conv_filters:
  - 32
  - 32
  - 32
  dropout_rate: 0.5
  fc_dim: 512
  ica_components: 64
  kernel_sizes:
  - - 5
    - 3
  - - 3
    - 3
  - - 3
    - 3
  siamese:
    embedding_dim: 512
    hidden_dim: 256
    margin: 1.0
preprocessing:
  channels:
    select: false
    set: epoc_x
  filter:
    apply: true
    highcut: 50.0
    lowcut: 1.0
  normalize: true
  resample:
    apply: false
    freq: 128
training:
  early_stopping: true
  epochs: 50
  learning_rate: 0.0003
  optimizer: adam
  patience: 10
  use_gpu: true
  weight_decay: 0.0001
windowing:
  window_length: 0.5
  window_stride: 0.25
